org.gradle.jvmargs=-Xmx2G -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

group=me.kvdpxne
version=0.1.0
description=Uniwersalny szablon projektu Java
url=https://github.com/mcdtm/time-synchronizer

license.name=MIT License
license.url=https://opensource.org/licenses/MIT

developer.id=kvdpxne
developer.name=kvdpxne

scm.connection=scm:git:git://github.com/mcdtm/time-synchronizer.git
scm.developerConnection=scm:git:ssh://github.com/mcdtm/time-synchronizer.git
scm.url=https://github.com/mcdtm/time-synchronizer