name: 'VoidChunkGenerator'
version: '${version}'
main: 'me.kvdpxne.vcg.VoidChunkGenPlugin'
load: 'STARTUP'
authors: [ 'kvdpxne', 'mcdtm team' ]
description: '${description}'
website: 'https://github.com/mcdtm/void-chuk-generator/'
